# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - public_repo
          #  - read:user
          #  - read:org
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: initmd
          template: classic
          base: header, activity, community, repositories, metadata
          config_octicon: yes
          config_timezone: Europe/Paris
          config_twemoji: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_fortune: yes
          plugin_habits: yes
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_lines: yes
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music: yes
          plugin_music_mode: recent
          plugin_music_provider: youtube
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_sponsors_custom: vignetteapp, infi, insertish
          plugin_people_thanks: insertish, infi
          plugin_people_types: followers, following
          plugin_posts: yes
          plugin_posts_limit: 4
          plugin_posts_source: dev.to
          plugin_posts_user: initmd
          plugin_projects: yes
          plugin_projects_limit: 4
          plugin_projects_repositories: mirukucafe/projects/1
          plugin_sponsors: yes
          plugin_sponsors_sections: goal
